[server]
headless = true
maxUploadSize = 50

[theme]
primaryColor = "#C7A76D"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F7FAFC"
textColor = "#1a365d"
font = "sans serif"

[browser]
gatherUsageStats = false
